version: '3'

services:
  plum-1:
    container_name: plum-1
    image: yoseplee/plum:0.2
    working_dir: /plum/
    ports:
      - "32120:50051"
  plum-2:
    container_name: plum-2
    image: yoseplee/plum:0.2
    working_dir: /plum/
    ports:
      - "32121:50051"
  plum-3:
    container_name: plum-3
    image: yoseplee/plum:0.2
    working_dir: /plum/
    ports:
      - "32122:50051"
  plum-4:
    container_name: plum-4
    image: yoseplee/plum:0.2
    working_dir: /plum/
    ports:
      - "32123:50051"
  plum-5:
    container_name: plum-5
    image: yoseplee/plum:0.2
    working_dir: /plum/
    ports:
      - "32124:50051"